import "./__data-field/_type/message-form__data-field_type_input.scss"
import "./__data-field/_type/message-form__data-field_type_textarea.scss"
import "./message-form.scss"
import "./message-form__button.scss"
import "./__tooltip/message-form__tooltip.js"
import "./__tooltip/message-form__tooltip.scss"
import "./__tooltip/_color/message-form__tooltip_color_orange-red.scss"
import "./__tooltip/_color/message-form__tooltip_color_cyan.scss"
