//UI-Kit components styles
import '../../fonts/fonts.scss'
import '../components/html/html.scss'

import '../../components/button/button'
import '../../components/button/button.scss'
import '../../components/arrow-buttons/arrow-buttons'
import '../../components/arrow-buttons/arrow-buttons.scss'
import '../../components/donut-chart/donut-chart.scss'
import '../../components/slider/slider'
import '../../components/slider/slider.scss'
import '../../components/message-form/message-form'
import '../../components/message-form/message-form.scss'
import '../../components/toggle/toggle.scss'
import '../../components/tick-box/tick-box.scss'
import '../../components/search-bar/search-bar.scss'
import '../../components/dropdown/dropdown.scss'
import '../../components/user-profile/user-profile.scss'
import '../../components/billboard/billboard.scss'
import '../../components/message-box/message-box'
import '../../components/message-box/message-box.scss'
import '../../components/map/map'
import '../../components/map/map.scss'
import '../../components/datepicker/datepicker'
import '../../components/datepicker/datepicker.scss'
import '../../components/video/video.scss'

//UI-Kit page's styles
import './components/header/header.scss'
import './components/block-sign/block-sign.scss'
import './components/buttons/buttons.scss'
import './components/arrows/arrows.scss'
import './components/charts/charts.scss'
import './components/sliders/sliders.scss'
import './components/stages-box/stages-box.scss'
import './components/form-elements/form-elements.scss'
import './components/toggles/toggles.scss'
import './components/tick-boxes/tick-boxes.scss'
import './components/search-dropdown-profiles/search-dropdown-profiles.scss'
import './components/search-dropdown/search-dropdown.scss'
import './components/profile/profile.scss'
import './components/news-events/news-events.scss'
import './components/location/location.scss'
import './components/calendar-messaging/calendar-messaging.scss'
import './components/calendar/calendar.scss'
import './components/messaging/messaging.scss'
import './components/video-box/video-box.scss'
