import "./user-photo__back.scss"
import "./user-photo__img.scss"

import "./_with-tooltip/user-photo_with-tooltip.scss"
import "./__tooltip/user-photo__tooltip.scss"
import "./__links/user-photo__links.scss"
import "./__links/_theme/user-photo__links_theme_cyan.scss"
import "./__links/_theme/user-photo__links_theme_orange-red.scss"
import "./__job/user-photo__job.scss"
import "./__name/user-photo__name.scss"
import "./__name/_color/user-photo__name_color_orange-red.scss"
import "./__name/_color/user-photo__name_color_white.scss"
import "./__job/_color/user-photo__job_color_black.scss"
import "./__job/_color/user-photo__job_color_white.scss"
import "./__tooltip/_color/user-photo__tooltip_color_cyan.scss"
import "./__tooltip/_color/user-photo__tooltip_color_grey.scss"
