import "./stages"
import "./stages__handle.scss"
import "./stages__scale.scss"
import "./__label/stages__line.scss"
import "./__label/stages__pip.scss"
import "./__label/stages__inrange.scss"
import "./__label/stages__text.scss"
import "./__label/stages__selected.scss"
