import "./billboard.scss"
import "./_background-color/billboard_background-color_cyan.scss"
import "./_background-color/billboard_background-color_orange-red.scss"
import "./billboard__content.scss"
import "./billboard__image.scss"
import "./billboard__description.scss"
import "./__date/billboard__date.scss"
import "./__date/_type/billboard__date_type_event.scss"
import "./__date/_type/billboard__date_type_new.scss"
import "./__title/billboard__title.scss"
import "./__title/_type/billboard__title_type_event.scss"
import "./__title/_type/billboard__title_type_new.scss"
import "./billboard__button.scss"

import "../button/button.styles"
